name: rss_shakha_app
description: R.S.S. Shakha Management App for Senior Citizens
publish_to: 'none'
version: 1.0.5+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  sqflite: ^2.3.3+1
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  audioplayers: ^6.0.0
  table_calendar: ^3.1.2
  wakelock_plus: ^1.2.8
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/audio/whistle.mp3
    - assets/data/personalities.json
    - assets/images/personalities/
  # fonts:
  #   - family: Noto Sans Devanagari
  #     fonts:
  #       - asset: assets/fonts/NotoSansDevanagari-Regular.ttf
  #       - asset: assets/fonts/NotoSansDevanagari-Bold.ttf
  #         weight: 700
